import { getSupabase } from "@/lib/supabase";

export interface Question {
  id: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

const QUIZZES: Record<string, Question[]> = {

  // ═══════════════════ CREDO ═══════════════════
  "01-deseo-de-dios": [
    { id: "q1", question: "¿Qué significa que el hombre es 'capaz de Dios'?", options: ["Que puede entender a Dios completamente", "Que está naturalmente abierto al conocimiento y amor de Dios", "Que merece ser tratado como un dios", "Que no necesita la Revelación divina"], correct: 1, explanation: "El CIC enseña que el deseo de Dios está inscrito en el corazón humano porque el hombre ha sido creado por Dios y para Dios (CIC 27)." },
    { id: "q2", question: "Según San Agustín, ¿dónde encuentra descanso el corazón humano?", options: ["En las riquezas y el poder", "En la sabiduría humana", "En Dios", "En la naturaleza"], correct: 2, explanation: "San Agustín dijo: 'Nos hiciste, Señor, para ti, y nuestro corazón está inquieto hasta que descanse en ti' (Confesiones I,1)." },
    { id: "q3", question: "¿Por qué se necesita la Revelación divina?", options: ["Porque Dios quiere ocultar la verdad", "Porque sin ella el hombre no puede conocer las verdades religiosas y morales necesarias", "Porque la razón humana lo puede todo", "Porque es una tradición cultural"], correct: 1, explanation: "Aunque la razón puede conocer a Dios, la Revelación es necesaria para conocer las verdades que superan la capacidad humana (CIC 38)." },
  ],
  "02-revelacion-de-dios": [
    { id: "q1", question: "¿Qué es la Tradición Apostólica?", options: ["Las costumbres culturales de la Iglesia", "La transmisión viva de la Palabra de Dios por los Apóstoles y sus sucesores", "Un conjunto de libros antiguos", "Las leyes de la Iglesia"], correct: 1, explanation: "La Tradición transmite íntegramente la Palabra de Dios confiada por Cristo a los Apóstoles (CIC 81)." },
    { id: "q2", question: "¿Qué contiene la Sagrada Escritura?", options: ["Solo el Nuevo Testamento", "La Palabra de Dios puesta por escrito bajo la inspiración del Espíritu Santo", "Reglas y normas de conducta", "Textos históricos sin inspiración divina"], correct: 1, explanation: "Dios inspiró a los autores humanos de los libros sagrados; por eso se dice que Dios es el autor de la Sagrada Escritura (CIC 105-106)." },
    { id: "q3", question: "¿Qué relación hay entre Escritura y Tradición?", options: ["Son rivales que se contradicen", "La Escritura anula la Tradición", "Están íntimamente unidas, brotan de la misma fuente divina", "La Tradición es más importante que la Escritura"], correct: 2, explanation: "Ambas brotan de la misma fuente divina, forman un solo depósito sagrado de la Palabra de Dios (CIC 80, 97)." },
  ],
  "03-dios-es-padre": [
    { id: "q1", question: "¿Qué significa que Dios es Padre?", options: ["Que Dios es como un padre humano pero más poderoso", "Que Dios es el origen de todo y cuida de su creación con amor", "Que Dios es solo una figura masculina", "Que Dios es distante y autoritario"], correct: 1, explanation: "Dios es Padre en el sentido de ser la fuente de todo ser y de amarnos con un amor infinito y personal (CIC 239, 270)." },
    { id: "q2", question: "¿Qué significa que Dios es todopoderoso?", options: ["Que puede hacer cualquier cosa, incluso el mal", "Que su poder es ilimitado pero siempre actúa según su sabiduría y amor", "Que controla nuestras vidas como títeres", "Que puede contradecirse a sí mismo"], correct: 1, explanation: "Dios es todopoderoso porque puede hacer todo lo que quiere, pero su voluntad es siempre buena y sabia (CIC 271)." },
    { id: "q3", question: "¿Por qué creemos en un solo Dios?", options: ["Porque es más sencillo que creer en muchos", "Porque Dios mismo se reveló como único en el Antiguo y Nuevo Testamento", "Porque los filósofos lo decidieron", "Porque cada cultura puede tener su propio dios"], correct: 1, explanation: "La fe cristiana confiesa que hay un solo Dios, por naturaleza, substancia y esencia (CIC 200), revelado en la Escritura." },
  ],
  "04-jesucristo-dios-y-hombre": [
    { id: "q1", question: "¿Quién es Jesucristo?", options: ["Un gran profeta", "Un maestro iluminado", "El Hijo de Dios hecho hombre, verdadero Dios y verdadero hombre", "Un ángel enviado por Dios"], correct: 2, explanation: "Jesucristo es la segunda Persona de la Santísima Trinidad que asumió la naturaleza humana sin dejar de ser Dios (CIC 464, 467)." },
    { id: "q2", question: "¿Por qué se hizo hombre el Hijo de Dios?", options: ["Para experimentar la vida humana", "Para salvarnos reconciliándonos con Dios y para que conozcamos el amor de Dios", "Para demostrar su poder", "Por curiosidad"], correct: 1, explanation: "El Verbo se encarnó para salvarnos reconciliándonos con Dios, para manifestarnos el amor divino y para ser modelo de santidad (CIC 457-459)." },
  ],
  "05-la-encarnacion": [
    { id: "q1", question: "¿Qué significa que «el Verbo se hizo carne» (Jn 1,14)?", options: ["Que Dios se disfrazó de hombre para enseñarnos", "Que Dios asumió verdaderamente la naturaleza humana entera, con su fragilidad", "Que Jesús era solo un hombre iluminado por la sabiduría divina", "Que Dios abandonó su divinidad al hacerse hombre"], correct: 1, explanation: "El Catecismo enseña que Dios no tomó un cuerpo de apariencia, sino que asumió nuestra naturaleza completa (CIC 456-457)." },
    { id: "q2", question: "Según el Concilio de Calcedonia (año 451), ¿cómo se define la unión de lo divino y lo humano en Cristo?", options: ["Dos personas y dos naturalezas separadas", "Una sola naturaleza que mezcla lo divino y lo humano", "Una sola Persona en dos naturalezas, sin confusión ni separación", "Dos personas que comparten una misma naturaleza divina"], correct: 2, explanation: "Calcedonia definió que Cristo es «una sola Persona en dos naturalezas», sin confusión, sin cambio, sin división y sin separación (CIC 467)." },
    { id: "q3", question: "¿Qué enseña la Iglesia sobre la virginidad de María?", options: ["María fue virgen solo antes del parto", "María fue virgen antes del parto, en el parto y después del parto", "María fue virgen solo hasta el nacimiento de Jesús", "La virginidad de María es solo un símbolo espiritual"], correct: 1, explanation: "La Iglesia profesa que María fue virgen antes del parto, en el parto y después del parto (CIC 499)." },
  ],
  "06-el-espiritu-santo": [
    { id: "q1", question: "¿Qué es el Espíritu Santo según la fe católica?", options: ["Una fuerza o energía impersonal", "La tercera Persona de la Trinidad, consustancial al Padre y al Hijo", "Un ángel superior enviado por Dios", "La manifestación del amor humano elevado por la gracia"], correct: 1, explanation: "El Espíritu Santo es la tercera Persona de la Santísima Trinidad, consustancial al Padre y al Hijo (CIC 685)." },
    { id: "q2", question: "¿Cuántos son los dones del Espíritu Santo?", options: ["Doce dones", "Siete dones: sabiduría, inteligencia, consejo, fortaleza, ciencia, piedad y temor de Dios", "Tres dones que corresponden a las virtudes teologales", "Diez dones que reflejan los mandamientos"], correct: 1, explanation: "El Espíritu Santo trae siete dones que nos hacen dóciles a la inspiración divina (CIC 1830-1831)." },
    { id: "q3", question: "¿Qué significa la palabra «Paráclito» con la que Jesús se refiere al Espíritu Santo?", options: ["«El que juzga»", "«El que manda»", "«El que está al lado»: consolador, defensor y abogado", "«El que ilumina»"], correct: 2, explanation: "Paráclito significa «el que está al lado»: consolador, defensor, abogado (CIC 683-684)." },
  ],
  "07-la-santisima-trinidad": [
    { id: "q1", question: "¿Cuál es el misterio central de la fe cristiana?", options: ["La resurrección de Cristo", "La creación del universo de la nada", "El misterio de la Santísima Trinidad", "El nacimiento virginal de Jesús"], correct: 2, explanation: "«El misterio de la Santísima Trinidad es el misterio central de la fe y de la vida cristiana» (CIC 234)." },
    { id: "q2", question: "¿Qué distingue al Padre, al Hijo y al Espíritu Santo entre sí?", options: ["Su naturaleza divina", "Las relaciones entre ellos, no lo que son en esencia", "El grado de poder que ejerce cada uno", "La época histórica en que se manifiestan"], correct: 1, explanation: "Lo que distingue a las Personas divinas no es lo que son, sino las relaciones entre ellas (CIC 252-255)." },
    { id: "q3", question: "¿Cómo se refleja la Trinidad en el bautismo de Jesús?", options: ["Jesús se bautiza a sí mismo", "El Hijo es bautizado, el Espíritu desciende como paloma y la voz del Padre se oye desde el cielo", "Tres ángeles descienden sobre Jesús", "El Padre y el Espíritu adoptan forma humana"], correct: 1, explanation: "En el bautismo de Jesús (Mt 3,16-17) se manifiestan las tres Personas divinas (CIC 236, 535)." },
  ],
  "08-creacion-y-providencia": [
    { id: "q1", question: "¿Por qué creó Dios el mundo?", options: ["Por necesidad", "Por amor, porque el amor tiende a compartirse y derramarse", "Por casualidad", "Por obligación"], correct: 1, explanation: "Dios creó no por necesidad, sino por amor. El amor tiende a compartirse (CIC 279-280)." },
    { id: "q2", question: "¿Qué significa «creatio ex nihilo»?", options: ["Que Dios formó el universo con materia preexistente", "Que Dios sacó el universo entero de la nada por su palabra y poder", "Que el universo surgió espontáneamente", "Que Dios creó el mundo a partir de su propia sustancia"], correct: 1, explanation: "Dios sacó el universo entero de la nada por su palabra (CIC 293-295)." },
    { id: "q3", question: "¿Qué es la divina providencia?", options: ["La predestinación sin libre albedrío", "La disposición con la que Dios conduce su obra hacia la perfección", "La intervención divina solo en milagros", "El funcionamiento autónomo de las leyes naturales"], correct: 1, explanation: "«La providencia es la disposición con la que Dios conduce su obra hacia la perfección» (CIC 302-305)." },
  ],
  "09-el-hombre-y-el-pecado": [
    { id: "q1", question: "¿Qué significa que el ser humano fue creado «a imagen de Dios»?", options: ["Que tiene apariencia física semejante a Dios", "Que es capaz de conocer y amar a su Creador", "Que posee el mismo poder creador que Dios", "Que es una emanación de la sustancia divina"], correct: 1, explanation: "«Entre todas las criaturas visibles, solo el hombre es capaz de conocer y amar a su Creador» (CIC 356-357)." },
    { id: "q2", question: "¿Qué es el pecado original?", options: ["Una culpa personal que cada persona comete al nacer", "Una herida en nuestra naturaleza que nos inclina al mal, transmitida a todos los descendientes de Adán", "Un mito simbólico sin consecuencias reales", "Un castigo divino irrevocable"], correct: 1, explanation: "El pecado original es una herida en nuestra naturaleza que nos inclina al mal, pero no tiene la última palabra (CIC 385-390, 404)." },
    { id: "q3", question: "¿Qué es el «Protoevangelio»?", options: ["El primer evangelio escrito por Mateo", "La promesa de redención en Génesis 3,15: la descendencia de la mujer aplastará la cabeza de la serpiente", "El anuncio del ángel a Zacarías", "La primera predicación de Pedro en Pentecostés"], correct: 1, explanation: "El Protoevangelio (Gn 3,15) es la primera promesa de redención: donde abundó el pecado, sobreabundó la gracia (CIC 410-421)." },
  ],
  "10-la-iglesia-pueblo-de-dios": [
    { id: "q1", question: "¿Cuándo fue manifestada la Iglesia al mundo?", options: ["En la Última Cena", "En Pentecostés, cuando el Espíritu Santo descendió sobre los apóstoles", "En el Concilio de Nicea del año 325", "Cuando Jesús nació en Belén"], correct: 1, explanation: "La Iglesia fue manifestada por el Espíritu Santo en Pentecostés (CIC 758-768)." },
    { id: "q2", question: "¿Cuáles son las cuatro marcas de la verdadera Iglesia?", options: ["Una, Santa, Católica y Apostólica", "Pobre, Obediente, Misionera y Santa", "Primitiva, Reformada, Carismática y Apostólica", "Petrina, Mariana, Eucarística y Misionera"], correct: 0, explanation: "Las cuatro marcas profesadas en el Credo son: Una, Santa, Católica y Apostólica (CIC 811-812)." },
    { id: "q3", question: "¿Cuál es la misión específica de los laicos?", options: ["Asistir a Misa los domingos", "Buscar el Reino de Dios transformando las realidades temporales", "Vivir en conventos", "Tener un ministerio oficial en la parroquia"], correct: 1, explanation: "Los laicos buscan el Reino de Dios ocupándose de las realidades temporales y ordenándolas según Dios (CIC 898-899)." },
  ],

  // ═══════════════════ SACRAMENTOS ═══════════════════
  "11-la-liturgia": [
    { id: "q1", question: "Según el Catecismo, ¿qué relación tiene la liturgia terrena con la liturgia celestial?", options: ["Es un simple recuerdo", "Es una anticipación y participación real en la liturgia del cielo", "Es una celebración completamente separada", "Solo los santos pueden participar en ambas"], correct: 1, explanation: "En la liturgia terrena pregustamos y participamos en la liturgia celestial (CIC 1090)." },
    { id: "q2", question: "¿Quién es el actor principal de toda celebración litúrgica?", options: ["El sacerdote que preside", "La asamblea de fieles reunida", "Cristo mismo, que actúa a través de los signos sacramentales", "El coro y los ministros"], correct: 2, explanation: "Cristo mismo actúa en la liturgia para realizar la obra de la salvación (CIC 1088)." },
    { id: "q3", question: "¿Quién es la fuente y el fin de toda la liturgia?", options: ["La Iglesia", "Dios Padre, de quien procede toda bendición", "El Espíritu Santo", "Los apóstoles"], correct: 1, explanation: "El Padre es la fuente y el fin de toda la liturgia: de Él procede toda bendición (CIC 1077-1083)." },
  ],
  "12-el-misterio-pascual": [
    { id: "q1", question: "¿Qué comprende el Misterio Pascual de Cristo?", options: ["Solo la Resurrección", "La Pasión, Muerte, Resurrección y Ascensión de Cristo", "Únicamente la Última Cena", "La Navidad y el ministerio público"], correct: 1, explanation: "El Misterio Pascual comprende la Pasión, Muerte, Resurrección y Ascensión de Jesucristo (CIC 1085, 571-655)." },
    { id: "q2", question: "Según San Pablo, ¿qué sucede con la fe si Cristo no ha resucitado?", options: ["Sigue siendo válida por su enseñanza moral", "La fe es vana y vacía, no tiene fundamento real", "Se convierte en una filosofía ética", "Perdura por la fuerza de la tradición"], correct: 1, explanation: "«Si Cristo no ha resucitado, vana es nuestra predicación y vana también la fe de ustedes» (1 Co 15,14; CIC 651)." },
    { id: "q3", question: "¿Cómo hace presente la liturgia el Misterio Pascual?", options: ["Mediante representaciones teatrales", "A través de la predicación", "Por la acción del Espíritu Santo, que actualiza la obra salvadora de Cristo", "Exclusivamente durante Semana Santa"], correct: 2, explanation: "Cristo está presente por la acción del Espíritu Santo, que actualiza su Misterio Pascual (CIC 1085-1090)." },
  ],
  "13-el-bautismo": [
    { id: "q1", question: "¿Por qué el Bautismo es llamado «la puerta de los sacramentos»?", options: ["Porque es el primer sacramento que se recibe en la vida adulta", "Porque sin él no se puede recibir válidamente ningún otro sacramento", "Porque es una tradición familiar", "Porque es el sacramento más importante"], correct: 1, explanation: "El Bautismo es la puerta que abre el acceso a los demás sacramentos (CIC 1213)." },
    { id: "q2", question: "¿Qué efecto produce el Bautismo respecto al pecado?", options: ["Solo perdona los pecados cometidos antes del bautismo", "Borra el pecado original y todos los pecados personales, así como toda pena debida por ellos", "Únicamente limpia el pecado original", "No afecta al pecado; solo nos incorpora a la comunidad"], correct: 1, explanation: "El Bautismo perdona todos los pecados y todas las penas debidas por el pecado (CIC 1263)." },
    { id: "q3", question: "¿Qué imprime el Bautismo en el alma?", options: ["Una marca visible externa", "Un carácter o sello espiritual indeleble que configura con Cristo", "Un don temporal que puede perderse", "Una gracia exclusiva para los deberes litúrgicos"], correct: 1, explanation: "El Bautismo imprime un carácter espiritual indeleble que permanece para siempre (CIC 1272-1274)." },
  ],
  "14-la-confirmacion": [
    { id: "q1", question: "¿Qué relación tiene la Confirmación con el Bautismo?", options: ["Es un sacramento independiente", "Perfecciona y completa la gracia bautismal, fortaleciendo al cristiano", "Reemplaza al Bautismo si fue recibido en la infancia", "Es un sacramento opcional"], correct: 1, explanation: "La Confirmación perfecciona la gracia bautismal (CIC 1285, 1303)." },
    { id: "q2", question: "¿Por qué la Confirmación imprime carácter?", options: ["No imprime carácter", "Porque el confirmado recibe una misión permanente de testimonio", "Imprime carácter solo para los varones", "Solo si se recibe de manos de un obispo"], correct: 1, explanation: "La Confirmación imprime un carácter indeleble porque configura al cristiano para una misión permanente (CIC 1304-1305)." },
    { id: "q3", question: "¿Qué significan la unción con el Santo Crisma y la imposición de manos?", options: ["Son gestos simbólicos sin efecto real", "Significan y realizan la efusión plena del Espíritu Santo y sus dones", "Representan la bienvenida a la comunidad", "Indican que se ha completado un curso de catequesis"], correct: 1, explanation: "La imposición de manos y la unción con el Santo Crisma realizan la efusión plena del Espíritu Santo (CIC 1293-1301)." },
  ],
  "15-la-eucaristia": [
    { id: "q1", question: "¿Cómo define el Catecismo a la Eucaristía?", options: ["Como una devoción piadosa entre muchas", "Como fuente y cumbre de toda la vida cristiana", "Como un rito secundario", "Como una conmemoración simbólica"], correct: 1, explanation: "La Eucaristía es «fuente y cumbre de toda la vida cristiana» (CIC 1324)." },
    { id: "q2", question: "¿En qué consiste la transubstanciación?", options: ["En que el pan y el vino simbolizan a Cristo", "En la conversión total de la sustancia del pan y del vino en el Cuerpo y la Sangre de Cristo", "En que Cristo se une al pan sin cambiarlo", "En un cambio solo perceptible por los místicos"], correct: 1, explanation: "Por la consagración se realiza la conversión de toda la sustancia del pan en el Cuerpo de Cristo (CIC 1376)." },
    { id: "q3", question: "¿Quiénes pueden consagrar válidamente la Eucaristía?", options: ["Todos los bautizados", "Solo los obispos y los presbíteros en comunión con ellos", "Cualquier persona designada por la comunidad", "Exclusivamente el Papa"], correct: 1, explanation: "Solo los presbíteros y obispos válidamente ordenados pueden consagrar, actuando in persona Christi (CIC 1411)." },
  ],
  "16-la-reconciliacion": [
    { id: "q1", question: "¿Qué parábola evangélica es el modelo de la Reconciliación?", options: ["La parábola del buen samaritano", "La parábola del hijo pródigo (o del padre misericordioso)", "La parábola del sembrador", "La parábola de las diez vírgenes"], correct: 1, explanation: "La parábola del hijo pródigo (Lc 15,11-32) revela el corazón misericordioso de Dios (CIC 1439)." },
    { id: "q2", question: "¿Cuáles son los tres actos esenciales del penitente?", options: ["Oración, ayuno y limosna", "Contrición, confesión y satisfacción", "Lectura bíblica, examen de conciencia y silencio", "Bautismo, comunión y confirmación"], correct: 1, explanation: "Los actos del penitente son contrición, confesión y satisfacción (CIC 1450-1460)." },
    { id: "q3", question: "¿Cuáles son los efectos principales de la Reconciliación?", options: ["Elimina solo la culpa", "La reconciliación con Dios y con la Iglesia, y la recuperación de la gracia santificante", "Solo devuelve la paz interior", "Proporciona consejos psicológicos"], correct: 1, explanation: "La Reconciliación nos reconcilia con Dios y con la Iglesia, recuperando la gracia santificante (CIC 1468-1470)." },
  ],
  "17-la-uncion": [
    { id: "q1", question: "¿Para quiénes está destinada la Unción de los Enfermos?", options: ["Solo para los moribundos", "Para todo fiel que empieza a estar en peligro de muerte por enfermedad grave o vejez", "Solo para enfermedades contagiosas", "Para cualquier dolencia leve"], correct: 1, explanation: "La Unción es para cualquier fiel que empieza a estar en peligro de muerte por enfermedad grave o vejez (CIC 1512-1513)." },
    { id: "q2", question: "¿Qué efectos produce la Unción de los Enfermos?", options: ["Garantiza la curación física", "Une al enfermo a la Pasión de Cristo, da paz, fortaleza y el perdón de los pecados", "Solo consuelo psicológico", "Libera de toda obligación moral futura"], correct: 1, explanation: "La Unción une al enfermo a la Pasión de Cristo y otorga paz, fortaleza y perdón (CIC 1520-1523)." },
    { id: "q3", question: "¿Quiénes pueden administrar este sacramento?", options: ["Todos los bautizados", "Solo los obispos y los presbíteros (sacerdotes)", "Los diáconos y ministros extraordinarios", "Cualquier cristiano en emergencia"], correct: 1, explanation: "Solo los presbíteros y obispos pueden administrar la Unción de los Enfermos (CIC 1516; Stg 5,14-15)." },
  ],
  "18-el-orden": [
    { id: "q1", question: "¿En nombre de quién actúa el sacerdote al celebrar los sacramentos?", options: ["En nombre de la comunidad", "En la persona de Cristo Cabeza (in persona Christi Capitis)", "En nombre de su propia santidad", "Como delegado de la autoridad civil"], correct: 1, explanation: "El sacerdote actúa in persona Christi Capitis; Cristo mismo actúa a través de él (CIC 1548-1551)." },
    { id: "q2", question: "¿Cuáles son los tres grados del sacramento del Orden?", options: ["Cardenal, arzobispo y obispo", "Diaconado, presbiterado y episcopado", "Lector, acólito y diácono", "Párroco, vicario y capellán"], correct: 1, explanation: "Los tres grados son episcopado, presbiterado y diaconado (CIC 1554, 1536)." },
    { id: "q3", question: "¿El Orden imprime carácter? ¿Qué significa?", options: ["No imprime carácter", "Sí, imprime un carácter indeleble que configura con Cristo para siempre", "Solo en los obispos", "Es revocable si hay pecado grave"], correct: 1, explanation: "El Orden imprime un carácter espiritual indeleble; quien ha sido ordenado permanece configurado con Cristo para siempre (CIC 1582-1583)." },
  ],
  "19-el-matrimonio": [
    { id: "q1", question: "¿A quién remite Jesús cuando habla del matrimonio?", options: ["A las leyes civiles romanas", "A la Ley de Moisés sobre el divorcio", "Al plan original de Dios «desde el principio»: los creó varón y mujer", "A las tradiciones culturales judías"], correct: 2, explanation: "Jesús remonta al origen: «¿No han leído que el Creador, desde el principio, los hizo varón y mujer?» (Mt 19,4; CIC 1603-1605)." },
    { id: "q2", question: "¿Cuáles son las dos propiedades esenciales del matrimonio?", options: ["Provisionalidad y flexibilidad", "Unidad e indisolubilidad", "Conveniencia económica y estabilidad social", "Compatibilidad y comunicación"], correct: 1, explanation: "Las propiedades esenciales son la unidad y la indisolubilidad (CIC 1644-1645)." },
    { id: "q3", question: "¿Qué hace el sacramento del Matrimonio en los esposos?", options: ["Los convierte en una asociación legal", "Les da fuerzas para cumplir sus deberes y los configura con el amor de Cristo por su Iglesia", "Sustituye el amor humano por uno espiritual", "Garantiza que no habrá dificultades"], correct: 1, explanation: "El sacramento concede la gracia de amarse con el amor con que Cristo amó a su Iglesia (CIC 1659-1661; Ef 5,25-33)." },
  ],
  "20-la-comunion": [
    { id: "q1", question: "¿Qué son los sacramentales?", options: ["Sacramentos menores administrados por laicos", "Signos sagrados instituidos por la Iglesia que imitan a los sacramentos", "Ritos mágicos heredados de tradiciones paganas", "Objetos de devoción sin relación con la liturgia"], correct: 1, explanation: "Los sacramentales son signos sagrados instituidos por la santa Madre Iglesia (CIC 1667)." },
    { id: "q2", question: "¿Cuál es la diferencia entre sacramento y sacramental?", options: ["No hay diferencia", "Los sacramentos obran ex opere operato; los sacramentales dependen de la fe de quien los usa", "Los sacramentales son más poderosos", "Los sacramentos son solo para ocasiones especiales"], correct: 1, explanation: "Los sacramentos obran ex opere operato; los sacramentales dependen de la fe del que los recibe (CIC 1667-1670)." },
    { id: "q3", question: "¿Qué carácter tienen las exequias cristianas?", options: ["Son ceremonias tristes de pérdida definitiva", "Celebran el Misterio Pascual del difunto, que participa de la muerte y resurrección de Cristo", "Son ritos sociales sin contenido teológico", "Se centran exclusivamente en los méritos del difunto"], correct: 1, explanation: "Las exequias cristianas celebran el Misterio Pascual del difunto iluminadas por la esperanza de la resurrección (CIC 1680-1690)." },
  ],

  // ═══════════════════ MORAL ═══════════════════
  "21-la-dignidad-humana": [
    { id: "q1", question: "Según el Catecismo, ¿de dónde proviene la dignidad de la persona humana?", options: ["De sus logros y productividad", "De haber sido creada a imagen y semejanza de Dios", "De su inteligencia natural", "Del reconocimiento de los demás"], correct: 1, explanation: "«La dignidad de la persona humana está enraizada en su creación a imagen y semejanza de Dios» (CIC 1700)." },
    { id: "q2", question: "¿Qué significa que la dignidad humana es «inalienable»?", options: ["Que puede perderse por crímenes graves", "Que solo la poseen personas virtuosas", "Que nadie puede arrebatarla porque es parte de lo que somos, no de lo que hacemos", "Que depende del estatus social"], correct: 2, explanation: "La dignidad es inalienable: no es algo que ganamos sino algo que somos (CIC 1700-1702)." },
    { id: "q3", question: "Según el CIC 1701, ¿quién revela plenamente el hombre al propio hombre?", options: ["La filosofía y las ciencias", "La educación y la cultura", "Cristo, el hombre nuevo", "El estado y las leyes civiles"], correct: 2, explanation: "«Cristo... manifiesta plenamente el hombre al propio hombre» (CIC 1701)." },
  ],
  "22-la-bienaventuranza": [
    { id: "q1", question: "¿Qué representan las Bienaventuranzas según el Catecismo?", options: ["Reglas morales imposibles", "El retrato del hombre verdaderamente feliz y el rostro de Cristo", "Consejos opcionales para los piadosos", "Promesas de prosperidad material"], correct: 1, explanation: "Las Bienaventuranzas «dibujan el rostro de Jesucristo... son el retrato del hombre verdaderamente feliz» (CIC 1716-1717)." },
    { id: "q2", question: "¿Cuál es la primera bienaventuranza y fundamento de todas?", options: ["Bienaventurados los mansos", "Bienaventurados los que lloran", "Bienaventurados los pobres de espíritu", "Bienaventurados los misericordiosos"], correct: 2, explanation: "La pobreza de espíritu (Mt 5,3) es la puerta de entrada porque solo quien reconoce su necesidad de Dios puede recibir el Reino (CIC 1717)." },
    { id: "q3", question: "¿Cuál es el fin último al que nos conducen las Bienaventuranzas?", options: ["La prosperidad terrena", "El bienestar emocional", "La visión beatífica: ver a Dios cara a cara", "La armonía social"], correct: 2, explanation: "«Dios nos llama a su propia bienaventuranza... la visión beatífica, la vida eterna» (CIC 1719)." },
  ],
  "23-la-libertad": [
    { id: "q1", question: "¿Cómo define el Catecismo la libertad humana?", options: ["La capacidad de hacer lo que uno desea sin restricciones", "El derecho a elegir sin consecuencias", "El poder, radicado en la razón y la voluntad, de obrar acciones deliberadas", "La ausencia total de normas"], correct: 2, explanation: "«La libertad es el poder, radicado en la razón y en la voluntad, de obrar o de no obrar» (CIC 1731)." },
    { id: "q2", question: "¿Qué relación hay entre libertad y responsabilidad?", options: ["La libertad elimina la responsabilidad", "Cuanto más libre es una persona, más responsable es de sus actos", "La responsabilidad solo existe con leyes externas", "Son conceptos independientes"], correct: 1, explanation: "«Mientras más se hace el bien, más libre se va haciendo uno» (CIC 1732)." },
    { id: "q3", question: "¿Qué puede disminuir la responsabilidad de una persona?", options: ["La ignorancia, el miedo, la violencia y los hábitos", "Los mandamientos divinos", "La educación en la virtud", "Una conciencia bien formada"], correct: 0, explanation: "La imputabilidad puede quedar disminuida por ignorancia, miedo, violencia o hábitos (CIC 1733-1735)." },
  ],
  "24-la-conciencia": [
    { id: "q1", question: "¿Qué es la conciencia moral?", options: ["Una opinión subjetiva personal", "El núcleo más secreto y el sagrario del hombre, donde resuena la voz de Dios", "Un instinto biológico", "Normas sociales interiorizadas"], correct: 1, explanation: "La conciencia es «el núcleo más secreto y el sagrario del hombre... donde resuena la voz de Dios» (CIC 1776)." },
    { id: "q2", question: "¿Debe siempre seguirse una conciencia cierta?", options: ["No, porque puede equivocarse", "Sí, pero solo si coincide con la mayoría", "Sí, incluso si es errónea, pero existe el grave deber de formarla correctamente", "No, solo si coincide con los sentimientos"], correct: 2, explanation: "«El hombre debe obedecer siempre el juicio cierto de su conciencia» pero debe formarla (CIC 1790-1793)." },
    { id: "q3", question: "¿Cuáles son los medios principales para formar la conciencia?", options: ["Las modas culturales", "La Palabra de Dios, la enseñanza de la Iglesia y el consejo de personas prudentes", "Los deseos espontáneos del corazón", "Las redes sociales"], correct: 1, explanation: "La conciencia se forma con la Palabra de Dios, la enseñanza de la Iglesia y los dones del Espíritu Santo (CIC 1783-1785)." },
  ],
  "25-las-virtudes": [
    { id: "q1", question: "¿Cómo define el Catecismo una virtud?", options: ["Un talento natural", "Un estado emocional pasajero", "Una disposición habitual y firme a hacer el bien", "Una obligación externa impuesta"], correct: 2, explanation: "«La virtud es una disposición habitual y firme a hacer el bien» (CIC 1803)." },
    { id: "q2", question: "¿Cuáles son las cuatro virtudes cardinales?", options: ["Fe, esperanza, caridad y humildad", "Prudencia, justicia, fortaleza y templanza", "Pobreza, castidad, obediencia y paciencia", "Oración, ayuno, limosna y penitencia"], correct: 1, explanation: "Las virtudes cardinales son prudencia, justicia, fortaleza y templanza (CIC 1805)." },
    { id: "q3", question: "¿Qué distingue a las virtudes teologales de las humanas?", options: ["Las teologales son adquiridas por esfuerzo humano", "Ambas son iguales en su origen", "Las teologales son infundidas por Dios, tienen como origen, motivo y objeto a Dios mismo", "Las humanas son más importantes"], correct: 2, explanation: "Las virtudes teologales son infundidas por Dios; tienen como origen, motivo y objeto a Dios (CIC 1812-1813)." },
  ],
  "26-el-pecado": [
    { id: "q1", question: "¿Qué es el pecado en su definición esencial?", options: ["Una infracción de normas sociales", "Un error psicológico sin consecuencias", "Una ofensa contra la razón, la verdad y la conciencia recta; un fracaso en el amor a Dios", "Un concepto anticuado sin aplicación moderna"], correct: 2, explanation: "«El pecado es una falta contra la razón, la verdad, la conciencia recta» (CIC 1849)." },
    { id: "q2", question: "¿Qué condiciones debe reunir un pecado para ser mortal?", options: ["Que sea público y con escándalo", "Materia grave, plena advertencia y pleno consentimiento", "Que la persona se sienta culpable", "Que sea repetido al menos tres veces"], correct: 1, explanation: "Se requieren tres condiciones: materia grave, plena advertencia y pleno consentimiento (CIC 1857)." },
    { id: "q3", question: "¿Cuál es la consecuencia del pecado mortal no confesado?", options: ["Pérdida temporal de paz interior", "Privación de la gracia santificante y, sin arrepentimiento, exclusión del Reino de Dios", "Una mancha leve purificable en la vida diaria", "Ninguna consecuencia real"], correct: 1, explanation: "El pecado mortal destruye la caridad y aparta al hombre de Dios (CIC 1861)." },
  ],
  "27-la-justicia": [
    { id: "q1", question: "La justicia es la virtud que consiste en:", options: ["Dar a cada uno lo que nos pide", "La constante y firme voluntad de dar a Dios y al prójimo lo que les es debido", "Asegurar que todos tengan lo mismo", "Castigar sin misericordia"], correct: 1, explanation: "«La justicia es la virtud moral que consiste en dar a Dios y al prójimo lo que les es debido» (CIC 1807)." },
    { id: "q2", question: "¿Qué gesto de Zaqueo demuestra la verdadera justicia?", options: ["Creer intelectualmente en Jesús", "Dar la mitad de sus bienes a los pobres y restituir cuatro veces lo defraudado", "Pedir disculpas genéricas", "Ofrecer sacrificios en el Templo"], correct: 1, explanation: "Zaqueo restituyó: la justicia no es opción decorativa del cristiano; es la estructura de la caridad (Lc 19,8-9; CIC 2412)." },
    { id: "q3", question: "Según la doctrina social de la Iglesia, la justicia social:", options: ["Es opcional para los cristianos", "Exige crear condiciones que permitan a todos vivir una vida digna", "Es incompatible con la propiedad privada", "Se reduce a dar limosna ocasional"], correct: 1, explanation: "La justicia social debe realizarse respetando la dignidad trascendente de la persona (CIC 1928-1942)." },
  ],
  "28-el-respeto": [
    { id: "q1", question: "¿Por qué la vida humana es sagrada?", options: ["Porque la sociedad la declara valiosa", "Porque Dios es su fuente y su fin, y la crea para sí mismo", "Porque es más valiosa que otras formas de vida", "Solo la vida de los inocentes es sagrada"], correct: 1, explanation: "«La vida humana es sagrada, porque desde su inicio es fruto de la acción creadora de Dios» (CIC 2258)." },
    { id: "q2", question: "¿Qué enseña la parábola del Buen Samaritano sobre quién es nuestro prójimo?", options: ["Solo familiares y amigos", "Quienes comparten nuestra fe", "Todo ser humano que sufre, sin importar su origen o condición", "Solo quienes nos han ayudado antes"], correct: 2, explanation: "El samaritano no pregunta si el herido merece ayuda: simplemente ve a otro ser humano que sufre (CIC 2259; Mt 25,40)." },
    { id: "q3", question: "¿Hasta cuándo se extiende la inviolabilidad de la vida humana?", options: ["Solo durante la infancia", "Desde la concepción hasta la muerte natural", "Desde el nacimiento hasta la senectud", "Solo cuando la persona es productiva"], correct: 1, explanation: "La vida debe ser protegida «desde el momento de la concepción» hasta la muerte natural (CIC 2270, 2276-2279)." },
  ],
  "29-la-verdad": [
    { id: "q1", question: "¿Por qué la verdad no es un concepto abstracto para el cristiano?", options: ["Porque la impone la Iglesia", "Porque la verdad es una Persona: Jesucristo, que dijo «Yo soy la Verdad»", "Porque la verdad es lo que cada uno siente", "Porque depende del consenso democrático"], correct: 1, explanation: "«En Jesucristo, la verdad de Dios se ha manifestado enteramente» (CIC 2466; Jn 14,6)." },
    { id: "q2", question: "¿Por qué Tomás Moro aceptó morir antes que jurar el Acta de Supremacía?", options: ["Por orgullo y terquedad", "Por deslealtad a su rey", "Porque no podía jurar una mentira: «Muero siendo buen servidor del rey, pero primero de Dios»", "Porque buscaba fama póstuma"], correct: 2, explanation: "Moro siguió CIC 2464 al no dar falso testimonio. La verdad no era negociable porque era fidelidad a Cristo." },
    { id: "q3", question: "¿Qué obligaciones implica el respeto a la verdad?", options: ["Decir siempre todo lo que sabemos", "Ser veraz, guardar secretos profesionales y evitar la calumnia", "Solo evitar mentiras graves", "Decir la verdad solo cuando conviene"], correct: 1, explanation: "«La veracidad implica la honestidad y la discreción. La justicia exige guardar secretos profesionales» (CIC 2469-2479)." },
  ],
  "30-la-sexualidad": [
    { id: "q1", question: "¿Cuál es la visión cristiana de la sexualidad?", options: ["Un instinto que debe reprimirse", "Un problema moral a superar", "Un don de Dios y una vocación al amor verdadero como don total de sí", "Una construcción cultural sin base natural"], correct: 2, explanation: "«La sexualidad... es ordenada al amor conyugal del hombre y de la mujer» (CIC 2331-2336)." },
    { id: "q2", question: "¿Qué significa que el cuerpo tiene un significado esponsal?", options: ["Que el matrimonio es una construcción social", "Que el cuerpo, en su masculinidad o feminidad, expresa la capacidad de ser don total para otro", "Que el género es completamente fluido", "Que el cuerpo no tiene significado más allá de lo biológico"], correct: 1, explanation: "«Cada uno de los sexos es imagen del poder y de la ternura de Dios» (CIC 2335)." },
    { id: "q3", question: "¿A qué vocación ordena la castidad la sexualidad?", options: ["A la represión del deseo", "Al amor conyugal, vivida en continencia según el estado de vida", "A la libertad sexual absoluta", "Exclusivamente a la procreación"], correct: 1, explanation: "«La castidad significa la integración lograda de la sexualidad en la persona» (CIC 2337-2349)." },
  ],
  "31-el-trabajo": [
    { id: "q1", question: "¿Es el trabajo un castigo del pecado original?", options: ["Sí, es enteramente consecuencia del pecado", "No, el trabajo pertenece a la condición original del ser humano; el sudor es la consecuencia del pecado", "Sí, y los cristianos deben evitarlo", "El trabajo no tiene relación con la fe"], correct: 1, explanation: "«El trabajo procede de personas creadas a imagen de Dios... El trabajo no es una maldición» (CIC 2427; Gn 2,15)." },
    { id: "q2", question: "¿A qué está ordenado el trabajo humano además de ganar el sustento?", options: ["Solo a acumular riqueza", "Al honor, la santificación personal y la colaboración en la obra de la creación", "Solo a la supervivencia", "Principalmente a competir"], correct: 1, explanation: "«El trabajo puede ser un medio de santificación» (CIC 2428)." },
    { id: "q3", question: "¿Qué derecho fundamental defiende la doctrina social de la Iglesia sobre el trabajo?", options: ["El derecho a no trabajar", "El derecho a un salario justo que permita una vida digna al trabajador y su familia", "El derecho al enriquecimiento ilimitado", "El derecho a explotar trabajadores"], correct: 1, explanation: "«El salario justo es el fruto legítimo del trabajo» (CIC 2434)." },
  ],
  "32-la-comunidad": [
    { id: "q1", question: "¿Por qué la fe cristiana no se puede vivir de forma puramente individual?", options: ["Porque Dios creó al hombre como ser social y la Iglesia es un cuerpo, no individuos aislados", "Porque la Iglesia lo impone arbitrariamente", "Porque la fe individual no tiene valor", "Sí se puede vivir sin comunidad"], correct: 0, explanation: "La persona humana necesita la vida social como exigencia de su naturaleza (CIC 1878; 1 Co 12)." },
    { id: "q2", question: "¿Qué impresionaba a los paganos de los primeros cristianos?", options: ["Su riqueza y poder", "Sus grandes templos", "Su amor visible y concreto: «Mirad cómo se aman entre sí»", "Su influencia política"], correct: 2, explanation: "Tertuliano atestigua que los paganos decían asombrados: «Ved cómo se aman entre sí» (Apologeticum 39,7)." },
    { id: "q3", question: "¿Cómo debe vivir la comunidad cristiana la solidaridad con los pobres?", options: ["Delegando toda ayuda al estado", "Como un deber de justicia y caridad, viendo a Cristo en el pobre", "Solo si demuestran que merecen ayuda", "Únicamente mediante la oración"], correct: 1, explanation: "«Es un deber de justicia y de caridad». «Cuanto hicisteis a estos hermanos míos más pequeños, a mí me lo hicisteis» (CIC 2443-2449; Mt 25,40)." },
  ],

  // ═══════════════════ ORACIÓN ═══════════════════
  "33-la-oracion-cristiana": [
    { id: "q1", question: "Según el Catecismo, ¿qué es la oración?", options: ["Un ritual obligatorio", "La elevación del alma a Dios o la petición de bienes convenientes", "Una técnica de meditación oriental", "Un deber exclusivo de sacerdotes y religiosos"], correct: 1, explanation: "San Juan Damasceno define la oración como «la elevación del alma a Dios o la petición a Dios de bienes convenientes» (CIC 2559)." },
    { id: "q2", question: "¿De dónde brota la oración según el Catecismo?", options: ["De la obligación religiosa", "Del corazón humano, de sus gozos y tristezas, de su búsqueda de Dios", "Solo de la lectura de la Biblia", "Exclusivamente de la liturgia"], correct: 1, explanation: "La oración brota de las fuentes de la vida: el corazón, la Escritura, la liturgia y las virtudes teologales (CIC 2650-2662)." },
    { id: "q3", question: "¿Cuáles son las tres grandes formas de oración?", options: ["Oración vocal, meditación y contemplación", "Petición, alabanza y acción de gracias", "El Padrenuestro, el Avemaría y el Gloria", "La misa, el rosario y la lectio divina"], correct: 0, explanation: "Las tres formas principales son la oración vocal, la meditación y la contemplación (CIC 2699, 2721-2724)." },
  ],
  "34-fuentes-de-la-oracion": [
    { id: "q1", question: "Según el Catecismo, ¿cuál es la primera fuente de la oración cristiana?", options: ["La liturgia de la Iglesia", "La Palabra de Dios (Sagrada Escritura)", "La tradición monástica", "Los escritos de los místicos"], correct: 1, explanation: "«La Palabra de Dios es la fuente de la oración cristiana»; la Iglesia exhorta a leer la Escritura porque «desconocer la Escritura es desconocer a Cristo» (CIC 2653)." },
    { id: "q2", question: "¿Qué es la «lectio divina»?", options: ["Un libro de oraciones medievales", "La lectura orante de la Sagrada Escritura en un clima de silencio y escucha", "Un tratado teológico sobre la contemplación", "El rezo comunitario del Oficio Divino"], correct: 1, explanation: "La lectio divina es la lectura orante de la Biblia practicada desde los Padres del desierto, con pasos de lectura, meditación, oración y contemplación (CIC 1177, 2708)." },
    { id: "q3", question: "¿Por qué la liturgia es fuente de oración?", options: ["Porque es la única oración válida", "Porque en la liturgia Cristo mismo ora y actúa, uniéndonos a su oración", "Porque es obligatoria los domingos", "Porque tiene música y cantos hermosos"], correct: 1, explanation: "En la liturgia es Cristo quien ora, alaba y da gracias; la oración litúrgica es oración de la Iglesia entera (CIC 1074, 2643)." },
  ],
  "35-tradicion-contemplativa": [
    { id: "q1", question: "¿Qué es la contemplación cristiana?", options: ["Una técnica de vacío mental", "Un estado de trance o éxtasis emocional", "La mirada sencilla y amorosa sobre Dios, un don y una gracia", "Una práctica exclusiva de monjes y ermitaños"], correct: 2, explanation: "Santa Teresa define la contemplación como «una mirada sencilla y amorosa sobre Dios». Es don, no técnica (CIC 2709-2713)." },
    { id: "q2", question: "¿Qué es el combate de la oración según el Catecismo?", options: ["Una lucha física contra enemigos visibles", "La resistencia a las distracciones, la sequedad y la pereza en la oración", "Una competencia para ver quién reza más", "La discusión teológica sobre la mejor forma de rezar"], correct: 1, explanation: "La oración es un combate contra nosotros mismos, contra las distracciones, la sequedad (acedia) y la tentación de abandonar (CIC 2726-2733)." },
    { id: "q3", question: "¿Cómo responde el Catecismo a la objeción «no sé rezar»?", options: ["Diciendo que solo los santos saben", "Afirmando que el Espíritu Santo mismo ora en nosotros y nos enseña a orar", "Recomendando leer manuales de espiritualidad", "Indicando que la oración no es necesaria para la salvación"], correct: 1, explanation: "«Nosotros no sabemos pedir como conviene, pero el Espíritu mismo intercede por nosotros» (Rm 8,26; CIC 741, 2736)." },
  ],
  "36-el-padre-nuestro": [
    { id: "q1", question: "¿Por qué el Padrenuestro es llamado «la oración del Señor»?", options: ["Porque fue compuesta por los apóstoles", "Porque fue enseñada y entregada por el mismo Jesús", "Porque es la más antigua de todas las oraciones", "Porque solo se reza en las misas solemnes"], correct: 1, explanation: "«El Padrenuestro es verdaderamente el resumen de todo el Evangelio», la oración que Jesús mismo enseñó a sus discípulos (CIC 2761, 2773)." },
    { id: "q2", question: "¿Qué significa llamar a Dios «Padre nuestro» (Abbá)?", options: ["Que Dios es una figura autoritaria y distante", "Una expresión de confianza filial, intimidad y pertenencia a la familia de Dios", "Que Dios es solo padre de Jesús, no nuestro", "Que podemos tratar a Dios con familiaridad irreverente"], correct: 1, explanation: "Llamar a Dios Abbá expresa la novedad de la oración cristiana: la confianza y la intimidad de hijos en el Hijo (CIC 2777-2780)." },
    { id: "q3", question: "¿Qué significa «hágase tu voluntad»?", options: ["Una resignación pasiva ante el destino", "La petición de que se realice el plan amoroso de Dios, uniéndonos a la obediencia de Cristo", "El deseo de imponer nuestra voluntad a Dios", "Que Dios haga lo que nosotros queremos"], correct: 1, explanation: "Pedimos que se realice el designio de benevolencia de Dios, uniendo nuestra voluntad a la de Cristo (CIC 2816-2825)." },
  ],
  "37-las-siete-peticiones": [
    { id: "q1", question: "¿Cómo se dividen las siete peticiones del Padrenuestro?", options: ["Cuatro hacia Dios y tres hacia nosotros", "Tres hacia Dios (teologales) y cuatro hacia nosotros (humanas)", "Todas se dirigen exclusivamente a Dios", "Es una división arbitraria sin significado"], correct: 1, explanation: "Las tres primeras se refieren a Dios: su Nombre, su Reino, su voluntad. Las cuatro últimas presentan nuestras necesidades (CIC 2803-2806)." },
    { id: "q2", question: "¿Qué pedimos en «danos hoy nuestro pan de cada día»?", options: ["Solo el pan material", "La confianza filial que espera de Dios el alimento cotidiano y el Pan de Vida (Eucaristía)", "Riquezas y abundancia material", "Solo la comunión eucarística"], correct: 1, explanation: "Pedimos el pan terreno y el Pan de Vida: la Eucaristía, anticipo del banquete del Reino (CIC 2835-2837)." },
    { id: "q3", question: "¿Qué significa «perdona nuestras ofensas como también nosotros perdonamos»?", options: ["Que el perdón divino depende de nuestro mérito", "Que el perdón de Dios y el que damos al prójimo son inseparables; el que no perdona no puede recibir el perdón", "Que Dios perdona incondicionalmente sin esperar nada de nosotros", "Que debemos perdonar solo a quienes lo merecen"], correct: 1, explanation: "«Este perdón no puede penetrar en nuestro corazón si no hemos perdonado a los que nos han ofendido» (CIC 2838-2845; Mt 6,14-15)." },
  ],


  // ENGLISH
    "01-desire-for-god": [
    { id: "q1", question: "What does it mean that man is 'capable of God'?", options: ["That he can understand God completely", "That he is naturally open to the knowledge and love of God", "That he deserves to be treated like a god", "That he does not need divine Revelation"], correct: 1, explanation: "The CCC teaches that the desire for God is inscribed in the human heart because man was created by God and for God (CCC 27)." },
    { id: "q2", question: "According to Saint Augustine, where does the human heart find rest?", options: ["In wealth and power", "In human wisdom", "In God", "In nature"], correct: 2, explanation: "Saint Augustine said: 'You have made us for yourself, O Lord, and our heart is restless until it rests in you' (Confessions I,1)." },
    { id: "q3", question: "Why is divine Revelation necessary?", options: ["Because God wants to hide the truth", "Because without it man cannot know the religious and moral truths necessary for salvation", "Because human reason can do everything", "Because it is a cultural tradition"], correct: 1, explanation: "Although reason can know God, Revelation is necessary to know truths that surpass human capacity (CCC 38)." },
  ],
    "02-divine-revelation": [
    { id: "q1", question: "What is Apostolic Tradition?", options: ["The cultural customs of the Church", "The living transmission of the Word of God by the Apostles and their successors", "A collection of ancient books", "The laws of the Church"], correct: 1, explanation: "Tradition transmits in its entirety the Word of God entrusted by Christ to the Apostles (CCC 81)." },
    { id: "q2", question: "What does Sacred Scripture contain?", options: ["Only the New Testament", "The Word of God committed to writing under the inspiration of the Holy Spirit", "Rules and norms of conduct", "Historical texts without divine inspiration"], correct: 1, explanation: "God inspired the human authors of the sacred books; for this reason God is said to be the author of Sacred Scripture (CCC 105-106)." },
    { id: "q3", question: "What is the relationship between Scripture and Tradition?", options: ["They are rivals that contradict each other", "Scripture nullifies Tradition", "They are intimately united, flowing from the same divine source", "Tradition is more important than Scripture"], correct: 2, explanation: "Both flow from the same divine source, forming a single sacred deposit of the Word of God (CCC 80, 97)." },
  ],
    "03-god-is-father": [
    { id: "q1", question: "What does it mean that God is Father?", options: ["That God is like a human father but more powerful", "That God is the origin of everything and cares for his creation with love", "That God is only a masculine figure", "That God is distant and authoritarian"], correct: 1, explanation: "God is Father in the sense of being the source of all being and of loving us with an infinite and personal love (CCC 239, 270)." },
    { id: "q2", question: "What does it mean that God is almighty?", options: ["That he can do anything, even evil", "That his power is unlimited but he always acts according to his wisdom and love", "That he controls our lives like puppets", "That he can contradict himself"], correct: 1, explanation: "God is almighty because he can do all that he wills, but his will is always good and wise (CCC 271)." },
    { id: "q3", question: "Why do we believe in one God?", options: ["Because it is simpler than believing in many", "Because God himself revealed himself as unique in the Old and New Testaments", "Because philosophers decided it", "Because each culture can have its own god"], correct: 1, explanation: "The Christian faith confesses that there is one God, by nature, substance, and essence (CCC 200), revealed in Scripture." },
  ],
    "04-jesus-christ-god-and-man": [
    { id: "q1", question: "Who is Jesus Christ?", options: ["A great prophet", "An enlightened teacher", "The Son of God made man, true God and true man", "An angel sent by God"], correct: 2, explanation: "Jesus Christ is the second Person of the Most Holy Trinity who assumed human nature without ceasing to be God (CCC 464, 467)." },
    { id: "q2", question: "Why did the Son of God become man?", options: ["To experience human life", "To save us by reconciling us with God and so that we might know God's love", "To demonstrate his power", "Out of curiosity"], correct: 1, explanation: "The Word became incarnate to save us by reconciling us with God, to manifest divine love to us, and to be a model of holiness (CCC 457-459)." },
  ],
    "05-the-incarnation": [
    { id: "q1", question: "What does it mean that 'the Word became flesh' (Jn 1:14)?", options: ["That God disguised himself as a man to teach us", "That God truly assumed the entire human nature, with its frailty", "That Jesus was merely a man enlightened by divine wisdom", "That God abandoned his divinity when he became man"], correct: 1, explanation: "The Catechism teaches that God did not take a body in appearance only, but assumed our complete nature (CCC 456-457)." },
    { id: "q2", question: "According to the Council of Chalcedon (AD 451), how is the union of the divine and the human in Christ defined?", options: ["Two persons and two separate natures", "One single nature mixing the divine and the human", "One single Person in two natures, without confusion or separation", "Two persons sharing one single divine nature"], correct: 2, explanation: "Chalcedon defined that Christ is 'one single Person in two natures,' without confusion, without change, without division, and without separation (CCC 467)." },
    { id: "q3", question: "What does the Church teach about Mary's virginity?", options: ["Mary was a virgin only before giving birth", "Mary was a virgin before birth, during birth, and after birth", "Mary was a virgin only until the birth of Jesus", "Mary's virginity is only a spiritual symbol"], correct: 1, explanation: "The Church professes that Mary was a virgin before birth, during birth, and after birth (CCC 499)." },
  ],
    "06-the-holy-spirit": [
    { id: "q1", question: "What is the Holy Spirit according to the Catholic faith?", options: ["An impersonal force or energy", "The third Person of the Trinity, consubstantial with the Father and the Son", "A superior angel sent by God", "The manifestation of human love elevated by grace"], correct: 1, explanation: "The Holy Spirit is the third Person of the Most Holy Trinity, consubstantial with the Father and the Son (CCC 685)." },
    { id: "q2", question: "How many are the gifts of the Holy Spirit?", options: ["Twelve gifts", "Seven gifts: wisdom, understanding, counsel, fortitude, knowledge, piety, and fear of the Lord", "Three gifts corresponding to the theological virtues", "Ten gifts reflecting the commandments"], correct: 1, explanation: "The Holy Spirit brings seven gifts that make us docile to divine inspiration (CCC 1830-1831)." },
    { id: "q3", question: "What does the word 'Paraclete,' used by Jesus to refer to the Holy Spirit, mean?", options: ["'The one who judges'", "'The one who commands'", "'The one who stands beside': consoler, defender, and advocate", "'The one who enlightens'"], correct: 2, explanation: "Paraclete means 'the one who stands beside': consoler, defender, advocate (CCC 683-684)." },
  ],
    "07-the-holy-trinity": [
    { id: "q1", question: "What is the central mystery of the Christian faith?", options: ["The resurrection of Christ", "The creation of the universe out of nothing", "The mystery of the Most Holy Trinity", "The virginal birth of Jesus"], correct: 2, explanation: "'The mystery of the Most Holy Trinity is the central mystery of the Christian faith and of Christian life' (CCC 234)." },
    { id: "q2", question: "What distinguishes the Father, the Son, and the Holy Spirit from one another?", options: ["Their divine nature", "The relations among them, not what they are in essence", "The degree of power each exercises", "The historical era in which they are manifested"], correct: 1, explanation: "What distinguishes the divine Persons is not what they are, but the relations among them (CCC 252-255)." },
    { id: "q3", question: "How is the Trinity reflected at the baptism of Jesus?", options: ["Jesus baptizes himself", "The Son is baptized, the Spirit descends like a dove, and the Father's voice is heard from heaven", "Three angels descend upon Jesus", "The Father and the Spirit take human form"], correct: 1, explanation: "At Jesus' baptism (Mt 3:16-17) the three divine Persons are manifested (CCC 236, 535)." },
  ],
    "08-creation-and-providence": [
    { id: "q1", question: "Why did God create the world?", options: ["Out of necessity", "Out of love, because love tends to share and pour itself out", "By chance", "Out of obligation"], correct: 1, explanation: "God created not out of necessity, but out of love. Love tends to share itself (CCC 279-280)." },
    { id: "q2", question: "What does 'creatio ex nihilo' mean?", options: ["That God formed the universe from pre-existing matter", "That God brought forth the entire universe from nothing by his word and power", "That the universe arose spontaneously", "That God created the world from his own substance"], correct: 1, explanation: "God brought forth the entire universe from nothing by his word (CCC 293-295)." },
    { id: "q3", question: "What is divine providence?", options: ["Predestination without free will", "The dispositions by which God guides his work toward perfection", "Divine intervention only in miracles", "The autonomous functioning of natural laws"], correct: 1, explanation: "'Providence is the dispositions by which God guides his work toward perfection' (CCC 302-305)." },
  ],
    "09-man-and-sin": [
    { id: "q1", question: "What does it mean that the human being was created 'in the image of God'?", options: ["That he has a physical appearance similar to God", "That he is capable of knowing and loving his Creator", "That he possesses the same creative power as God", "That he is an emanation of the divine substance"], correct: 1, explanation: "'Among all visible creatures, only man is capable of knowing and loving his Creator' (CCC 356-357)." },
    { id: "q2", question: "What is original sin?", options: ["A personal guilt that each person commits at birth", "A wound in our nature that inclines us to evil, transmitted to all descendants of Adam", "A symbolic myth without real consequences", "An irrevocable divine punishment"], correct: 1, explanation: "Original sin is a wound in our nature that inclines us to evil, but it does not have the last word (CCC 385-390, 404)." },
    { id: "q3", question: "What is the 'Protoevangelium'?", options: ["The first gospel written by Matthew", "The promise of redemption in Genesis 3:15: the woman's offspring will crush the serpent's head", "The angel's announcement to Zechariah", "Peter's first preaching at Pentecost"], correct: 1, explanation: "The Protoevangelium (Gen 3:15) is the first promise of redemption: where sin abounded, grace superabounded (CCC 410-421)." },
  ],
    "10-the-church-people-of-god": [
    { id: "q1", question: "When was the Church made manifest to the world?", options: ["At the Last Supper", "At Pentecost, when the Holy Spirit descended upon the apostles", "At the Council of Nicaea in AD 325", "When Jesus was born in Bethlehem"], correct: 1, explanation: "The Church was made manifest by the Holy Spirit at Pentecost (CCC 758-768)." },
    { id: "q2", question: "What are the four marks of the true Church?", options: ["One, Holy, Catholic, and Apostolic", "Poor, Obedient, Missionary, and Holy", "Primitive, Reformed, Charismatic, and Apostolic", "Petrine, Marian, Eucharistic, and Missionary"], correct: 0, explanation: "The four marks professed in the Creed are: One, Holy, Catholic, and Apostolic (CCC 811-812)." },
    { id: "q3", question: "What is the specific mission of the laity?", options: ["To attend Mass on Sundays", "To seek the Kingdom of God by transforming temporal realities", "To live in convents", "To hold an official ministry in the parish"], correct: 1, explanation: "The laity seek the Kingdom of God by engaging in temporal realities and ordering them according to God (CCC 898-899)." },
  ],
   "11-the-liturgy": [
    { id: "q1", question: "According to the Catechism, what is the relationship between the earthly liturgy and the heavenly liturgy?", options: ["It is a mere remembrance", "It is an anticipation and real participation in the liturgy of heaven", "It is a completely separate celebration", "Only the saints can participate in both"], correct: 1, explanation: "In the earthly liturgy we foretaste and participate in the heavenly liturgy (CCC 1090)." },
    { id: "q2", question: "Who is the principal actor in every liturgical celebration?", options: ["The presiding priest", "The assembly of the faithful gathered", "Christ himself, who acts through the sacramental signs", "The choir and ministers"], correct: 2, explanation: "Christ himself acts in the liturgy to accomplish the work of salvation (CCC 1088)." },
    { id: "q3", question: "Who is the source and goal of all liturgy?", options: ["The Church", "God the Father, from whom every blessing comes", "The Holy Spirit", "The apostles"], correct: 1, explanation: "The Father is the source and goal of all liturgy: from Him every blessing flows (CCC 1077-1083)." },
  ],
  "12-the-paschal-mystery": [
    { id: "q1", question: "What does the Paschal Mystery of Christ encompass?", options: ["Only the Resurrection", "The Passion, Death, Resurrection, and Ascension of Christ", "Only the Last Supper", "Christmas and the public ministry"], correct: 1, explanation: "The Paschal Mystery encompasses the Passion, Death, Resurrection, and Ascension of Jesus Christ (CCC 1085, 571-655)." },
    { id: "q2", question: "According to St. Paul, what happens to faith if Christ has not been raised?", options: ["It remains valid because of his moral teaching", "Faith is vain and empty, it has no real foundation", "It becomes an ethical philosophy", "It endures through the force of tradition"], correct: 1, explanation: "\"If Christ has not been raised, then our preaching is in vain and your faith is in vain\" (1 Cor 15:14; CCC 651)." },
    { id: "q3", question: "How does the liturgy make the Paschal Mystery present?", options: ["Through theatrical representations", "Through preaching", "By the action of the Holy Spirit, who actualizes the saving work of Christ", "Exclusively during Holy Week"], correct: 2, explanation: "Christ is present by the action of the Holy Spirit, who actualizes his Paschal Mystery (CCC 1085-1090)." },
  ],
  "13-baptism": [
    { id: "q1", question: "Why is Baptism called \"the gateway to the sacraments\"?", options: ["Because it is the first sacrament received in adult life", "Because without it no other sacrament can be validly received", "Because it is a family tradition", "Because it is the most important sacrament"], correct: 1, explanation: "Baptism is the gateway that opens access to the other sacraments (CCC 1213)." },
    { id: "q2", question: "What effect does Baptism have regarding sin?", options: ["It only forgives sins committed before baptism", "It erases original sin and all personal sins, as well as all punishment due for them", "It only cleanses original sin", "It does not affect sin; it only incorporates us into the community"], correct: 1, explanation: "Baptism forgives all sins and all punishments due for sin (CCC 1263)." },
    { id: "q3", question: "What does Baptism imprint on the soul?", options: ["A visible external mark", "An indelible spiritual character or seal that configures one to Christ", "A temporary gift that can be lost", "A grace exclusive to liturgical duties"], correct: 1, explanation: "Baptism imprints an indelible spiritual character that remains forever (CCC 1272-1274)." },
  ],
  "14-confirmation": [
    { id: "q1", question: "What relationship does Confirmation have with Baptism?", options: ["It is an independent sacrament", "It perfects and completes baptismal grace, strengthening the Christian", "It replaces Baptism if received in infancy", "It is an optional sacrament"], correct: 1, explanation: "Confirmation perfects baptismal grace (CCC 1285, 1303)." },
    { id: "q2", question: "Why does Confirmation imprint a character?", options: ["It does not imprint a character", "Because the confirmed person receives a permanent mission of witness", "It imprints a character only for males", "Only if received from a bishop"], correct: 1, explanation: "Confirmation imprints an indelible character because it configures the Christian for a permanent mission (CCC 1304-1305)." },
    { id: "q3", question: "What do the anointing with Sacred Chrism and the laying on of hands signify?", options: ["They are symbolic gestures without real effect", "They signify and effect the full outpouring of the Holy Spirit and his gifts", "They represent welcome to the community", "They indicate completion of a catechesis course"], correct: 1, explanation: "The laying on of hands and anointing with Sacred Chrism effect the full outpouring of the Holy Spirit (CCC 1293-1301)." },
  ],
  "15-the-eucharist": [
    { id: "q1", question: "How does the Catechism define the Eucharist?", options: ["As one pious devotion among many", "As the source and summit of the entire Christian life", "As a secondary rite", "As a symbolic commemoration"], correct: 1, explanation: "The Eucharist is \"the source and summit of the Christian life\" (CCC 1324)." },
    { id: "q2", question: "What does transubstantiation consist of?", options: ["Bread and wine symbolizing Christ", "The total conversion of the substance of bread and wine into the Body and Blood of Christ", "Christ uniting himself to the bread without changing it", "A change perceptible only to mystics"], correct: 1, explanation: "By the consecration, the conversion of the whole substance of the bread into the Body of Christ takes place (CCC 1376)." },
    { id: "q3", question: "Who can validly consecrate the Eucharist?", options: ["All the baptized", "Only bishops and priests in communion with them", "Any person designated by the community", "Exclusively the Pope"], correct: 1, explanation: "Only validly ordained priests and bishops can consecrate, acting in persona Christi (CCC 1411)." },
  ],
  "16-reconciliation": [
    { id: "q1", question: "Which Gospel parable is the model for Reconciliation?", options: ["The parable of the Good Samaritan", "The parable of the Prodigal Son (or the Merciful Father)", "The parable of the Sower", "The parable of the Ten Virgins"], correct: 1, explanation: "The parable of the Prodigal Son (Lk 15:11-32) reveals the merciful heart of God (CCC 1439)." },
    { id: "q2", question: "What are the three essential acts of the penitent?", options: ["Prayer, fasting, and almsgiving", "Contrition, confession, and satisfaction", "Scripture reading, examination of conscience, and silence", "Baptism, communion, and confirmation"], correct: 1, explanation: "The acts of the penitent are contrition, confession, and satisfaction (CCC 1450-1460)." },
    { id: "q3", question: "What are the principal effects of Reconciliation?", options: ["It removes only guilt", "Reconciliation with God and with the Church, and the recovery of sanctifying grace", "It only restores inner peace", "It provides psychological counsel"], correct: 1, explanation: "Reconciliation reconciles us with God and with the Church, recovering sanctifying grace (CCC 1468-1470)." },
  ],
  "17-anointing": [
    { id: "q1", question: "For whom is the Anointing of the Sick intended?", options: ["Only for the dying", "For any faithful person who begins to be in danger of death from serious illness or old age", "Only for contagious diseases", "For any minor ailment"], correct: 1, explanation: "Anointing is for any faithful who begins to be in danger of death from serious illness or old age (CCC 1512-1513)." },
    { id: "q2", question: "What effects does the Anointing of the Sick produce?", options: ["It guarantees physical healing", "It unites the sick person to the Passion of Christ, gives peace, strength, and forgiveness of sins", "Only psychological comfort", "It frees from all future moral obligations"], correct: 1, explanation: "Anointing unites the sick person to the Passion of Christ and grants peace, strength, and forgiveness (CCC 1520-1523)." },
    { id: "q3", question: "Who can administer this sacrament?", options: ["All the baptized", "Only bishops and priests", "Deacons and extraordinary ministers", "Any Christian in an emergency"], correct: 1, explanation: "Only priests and bishops can administer the Anointing of the Sick (CCC 1516; Jas 5:14-15)." },
  ],
  "18-holy-orders": [
    { id: "q1", question: "In whose name does the priest act when celebrating the sacraments?", options: ["In the name of the community", "In the person of Christ the Head (in persona Christi Capitis)", "In the name of his own holiness", "As a delegate of civil authority"], correct: 1, explanation: "The priest acts in persona Christi Capitis; Christ himself acts through him (CCC 1548-1551)." },
    { id: "q2", question: "What are the three degrees of the sacrament of Holy Orders?", options: ["Cardinal, archbishop, and bishop", "Diaconate, presbyterate, and episcopate", "Lector, acolyte, and deacon", "Pastor, vicar, and chaplain"], correct: 1, explanation: "The three degrees are episcopate, presbyterate, and diaconate (CCC 1554, 1536)." },
    { id: "q3", question: "Does Holy Orders imprint a character? What does that mean?", options: ["It does not imprint a character", "Yes, it imprints an indelible character that configures one to Christ forever", "Only in bishops", "It is revocable if there is grave sin"], correct: 1, explanation: "Holy Orders imprints an indelible spiritual character; one who has been ordained remains configured to Christ forever (CCC 1582-1583)." },
  ],
  "19-matrimony": [
    { id: "q1", question: "To what does Jesus refer when speaking about marriage?", options: ["Roman civil laws", "The Law of Moses on divorce", "God's original plan \"from the beginning\": he created them male and female", "Jewish cultural traditions"], correct: 2, explanation: "Jesus goes back to the origin: \"Have you not read that the Creator, from the beginning, made them male and female?\" (Mt 19:4; CCC 1603-1605)." },
    { id: "q2", question: "What are the two essential properties of marriage?", options: ["Provisionality and flexibility", "Unity and indissolubility", "Economic convenience and social stability", "Compatibility and communication"], correct: 1, explanation: "The essential properties are unity and indissolubility (CCC 1644-1645)." },
    { id: "q3", question: "What does the sacrament of Matrimony do for the spouses?", options: ["It turns them into a legal association", "It gives them strength to fulfill their duties and configures them with the love of Christ for his Church", "It replaces human love with spiritual love", "It guarantees there will be no difficulties"], correct: 1, explanation: "The sacrament grants the grace to love with the love with which Christ loved his Church (CCC 1659-1661; Eph 5:25-33)." },
  ],
  "20-sacramentals": [
    { id: "q1", question: "What are sacramentals?", options: ["Minor sacraments administered by laity", "Sacred signs instituted by the Church that imitate the sacraments", "Magical rites inherited from pagan traditions", "Devotional objects unrelated to the liturgy"], correct: 1, explanation: "Sacramentals are sacred signs instituted by Holy Mother Church (CCC 1667)." },
    { id: "q2", question: "What is the difference between a sacrament and a sacramental?", options: ["There is no difference", "Sacraments work ex opere operato; sacramentals depend on the faith of the one using them", "Sacramentals are more powerful", "Sacraments are only for special occasions"], correct: 1, explanation: "Sacraments work ex opere operato; sacramentals depend on the faith of the recipient (CCC 1667-1670)." },
    { id: "q3", question: "What character do Christian funerals have?", options: ["They are sad ceremonies of definitive loss", "They celebrate the Paschal Mystery of the deceased, who shares in the death and resurrection of Christ", "They are social rites without theological content", "They focus exclusively on the merits of the deceased"], correct: 1, explanation: "Christian funerals celebrate the Paschal Mystery of the deceased, illumined by the hope of the resurrection (CCC 1680-1690)." },
  ],
    "21-human-dignity": [
    { id: "q1", question: "According to the Catechism, where does the dignity of the human person come from?", options: ["From achievements and productivity", "From being created in the image and likeness of God", "From natural intelligence", "From the recognition of others"], correct: 1, explanation: "\"The dignity of the human person is rooted in his creation in the image and likeness of God\" (CCC 1700)." },
    { id: "q2", question: "What does it mean that human dignity is \"inalienable\"?", options: ["It can be lost through grave crimes", "Only virtuous people possess it", "No one can take it away because it is part of who we are, not what we do", "It depends on social status"], correct: 2, explanation: "Dignity is inalienable: it is not something we earn but something we are (CCC 1700-1702)." },
    { id: "q3", question: "According to CCC 1701, who fully reveals man to himself?", options: ["Philosophy and the sciences", "Education and culture", "Christ, the new man", "The state and civil laws"], correct: 2, explanation: "\"Christ... fully reveals man to man himself\" (CCC 1701)." },
  ],
    "22-the-beatitudes": [
    { id: "q1", question: "What do the Beatitudes represent according to the Catechism?", options: ["Impossible moral rules", "The portrait of the truly happy man and the face of Christ", "Optional advice for the pious", "Promises of material prosperity"], correct: 1, explanation: "The Beatitudes \"depict the countenance of Jesus Christ... they are the portrait of the man who is truly happy\" (CCC 1716-1717)." },
    { id: "q2", question: "Which is the first beatitude and foundation of all the others?", options: ["Blessed are the meek", "Blessed are those who mourn", "Blessed are the poor in spirit", "Blessed are the merciful"], correct: 2, explanation: "Poverty of spirit (Mt 5:3) is the gateway, because only those who recognize their need for God can receive the Kingdom (CCC 1717)." },
    { id: "q3", question: "What is the ultimate end to which the Beatitudes lead us?", options: ["Earthly prosperity", "Emotional well-being", "The beatific vision: seeing God face to face", "Social harmony"], correct: 2, explanation: "\"God calls us to his own beatitude... the beatific vision, eternal life\" (CCC 1719)." },
  ],
    "23-freedom": [
    { id: "q1", question: "How does the Catechism define human freedom?", options: ["The ability to do whatever one wants without restrictions", "The right to choose without consequences", "The power, rooted in reason and will, to perform deliberate actions", "The total absence of norms"], correct: 2, explanation: "\"Freedom is the power, rooted in reason and will, to act or not to act\" (CCC 1731)." },
    { id: "q2", question: "What is the relationship between freedom and responsibility?", options: ["Freedom eliminates responsibility", "The freer a person is, the more responsible they are for their actions", "Responsibility only exists with external laws", "They are independent concepts"], correct: 1, explanation: "\"The more one does what is good, the freer one becomes\" (CCC 1732)." },
    { id: "q3", question: "What can diminish a person's responsibility?", options: ["Ignorance, fear, violence, and habits", "The divine commandments", "Education in virtue", "A well-formed conscience"], correct: 0, explanation: "Imputability can be diminished by ignorance, fear, violence, or habits (CCC 1733-1735)." },
  ],
    "24-conscience": [
    { id: "q1", question: "What is the moral conscience?", options: ["A subjective personal opinion", "The most secret core and sanctuary of man, where the voice of God resounds", "A biological instinct", "Internalized social norms"], correct: 1, explanation: "Conscience is \"the most secret core and sanctuary of a man... where the voice of God echoes\" (CCC 1776)." },
    { id: "q2", question: "Must a certain conscience always be followed?", options: ["No, because it can be mistaken", "Yes, but only if it agrees with the majority", "Yes, even if it is erroneous, but there is a grave duty to form it correctly", "No, only if it agrees with one's feelings"], correct: 2, explanation: "\"Man must always obey the certain judgment of his conscience\" but must form it (CCC 1790-1793)." },
    { id: "q3", question: "What are the principal means for forming the conscience?", options: ["Cultural trends", "The Word of God, the teaching of the Church, and the advice of prudent people", "The spontaneous desires of the heart", "Social media"], correct: 1, explanation: "The conscience is formed by the Word of God, the teaching of the Church, and the gifts of the Holy Spirit (CCC 1783-1785)." },
  ],
    "25-virtues": [
    { id: "q1", question: "How does the Catechism define a virtue?", options: ["A natural talent", "A passing emotional state", "A habitual and firm disposition to do the good", "An externally imposed obligation"], correct: 2, explanation: "\"A virtue is a habitual and firm disposition to do the good\" (CCC 1803)." },
    { id: "q2", question: "What are the four cardinal virtues?", options: ["Faith, hope, charity, and humility", "Prudence, justice, fortitude, and temperance", "Poverty, chastity, obedience, and patience", "Prayer, fasting, almsgiving, and penance"], correct: 1, explanation: "The cardinal virtues are prudence, justice, fortitude, and temperance (CCC 1805)." },
    { id: "q3", question: "What distinguishes the theological virtues from the human virtues?", options: ["Theological virtues are acquired by human effort", "Both are equal in their origin", "The theological virtues are infused by God; they have God himself as their origin, motive, and object", "The human virtues are more important"], correct: 2, explanation: "The theological virtues are infused by God; they have God as their origin, motive, and object (CCC 1812-1813)." },
  ],
    "26-sin": [
    { id: "q1", question: "What is sin in its essential definition?", options: ["An infraction of social norms", "A psychological error without consequences", "An offense against reason, truth, and right conscience; a failure in love for God", "An outdated concept with no modern application"], correct: 2, explanation: "\"Sin is an offense against reason, truth, and right conscience\" (CCC 1849)." },
    { id: "q2", question: "What conditions must a sin meet to be mortal?", options: ["It must be public and cause scandal", "Grave matter, full knowledge, and full consent", "The person must feel guilty", "It must be repeated at least three times"], correct: 1, explanation: "Three conditions are required: grave matter, full knowledge, and full consent (CCC 1857)." },
    { id: "q3", question: "What is the consequence of unconfessed mortal sin?", options: ["Temporary loss of inner peace", "Privation of sanctifying grace and, without repentance, exclusion from the Kingdom of God", "A slight stain purifiable in daily life", "No real consequence"], correct: 1, explanation: "Mortal sin destroys charity and separates man from God (CCC 1861)." },
  ],
    "27-justice": [
    { id: "q1", question: "Justice is the virtue that consists in:", options: ["Giving each person what they ask for", "The constant and firm will to give God and neighbor what is due to them", "Ensuring everyone has the same", "Punishing without mercy"], correct: 1, explanation: "\"Justice is the moral virtue that consists in giving God and neighbor what is due to them\" (CCC 1807)." },
    { id: "q2", question: "What gesture of Zacchaeus demonstrates true justice?", options: ["Believing intellectually in Jesus", "Giving half of his goods to the poor and restoring fourfold what he had defrauded", "Offering generic apologies", "Offering sacrifices in the Temple"], correct: 1, explanation: "Zacchaeus made restitution: justice is not an optional decoration for the Christian; it is the structure of charity (Lk 19:8-9; CCC 2412)." },
    { id: "q3", question: "According to the Church's social doctrine, social justice:", options: ["Is optional for Christians", "Requires creating conditions that allow everyone to live a dignified life", "Is incompatible with private property", "Is reduced to giving occasional alms"], correct: 1, explanation: "Social justice must be realized while respecting the transcendent dignity of the person (CCC 1928-1942)." },
  ],
    "28-respect": [
    { id: "q1", question: "Why is human life sacred?", options: ["Because society declares it valuable", "Because God is its source and its end, and creates it for himself", "Because it is more valuable than other forms of life", "Only the life of the innocent is sacred"], correct: 1, explanation: "\"Human life is sacred, because from its beginning it is the fruit of God's creative action\" (CCC 2258)." },
    { id: "q2", question: "What does the parable of the Good Samaritan teach about who our neighbor is?", options: ["Only family and friends", "Those who share our faith", "Every human being who suffers, regardless of origin or condition", "Only those who have helped us before"], correct: 2, explanation: "The Samaritan does not ask whether the wounded man deserves help: he simply sees another human being who suffers (CCC 2259; Mt 25:40)." },
    { id: "q3", question: "Until when does the inviolability of human life extend?", options: ["Only during childhood", "From conception until natural death", "From birth until old age", "Only when the person is productive"], correct: 1, explanation: "Life must be protected \"from the moment of conception\" until natural death (CCC 2270, 2276-2279)." },
  ],
    "29-truth": [
    { id: "q1", question: "Why is truth not an abstract concept for a Christian?", options: ["Because the Church imposes it", "Because truth is a Person: Jesus Christ, who said \"I am the Truth\"", "Because truth is what each person feels", "Because it depends on democratic consensus"], correct: 1, explanation: "\"In Jesus Christ, the truth of God has been manifested entirely\" (CCC 2466; Jn 14:6)." },
    { id: "q2", question: "Why did Thomas More accept death rather than swear the Act of Supremacy?", options: ["Out of pride and stubbornness", "Out of disloyalty to his king", "Because he could not swear a lie: \"I die being the king's good servant, but God's first\"", "Because he sought posthumous fame"], correct: 2, explanation: "More followed CCC 2464 by not bearing false witness. Truth was not negotiable because it was fidelity to Christ." },
    { id: "q3", question: "What obligations does respect for the truth entail?", options: ["Always saying everything we know", "Being truthful, keeping professional secrets, and avoiding calumny", "Only avoiding serious lies", "Telling the truth only when convenient"], correct: 1, explanation: "\"Truthfulness entails honesty and discretion. Justice requires keeping professional secrets\" (CCC 2469-2479)." },
  ],
    "30-sexuality": [
    { id: "q1", question: "What is the Christian vision of sexuality?", options: ["An instinct that must be repressed", "A moral problem to overcome", "A gift from God and a vocation to authentic love as total self-gift", "A cultural construct with no natural basis"], correct: 2, explanation: "\"Sexuality... is ordered to the conjugal love of man and woman\" (CCC 2331-2336)." },
    { id: "q2", question: "What does it mean that the body has a spousal meaning?", options: ["That marriage is a social construct", "That the body, in its masculinity or femininity, expresses the capacity to be a total gift for another", "That gender is completely fluid", "That the body has no meaning beyond the biological"], correct: 1, explanation: "\"Each of the two sexes is an image of the power and tenderness of God\" (CCC 2335)." },
    { id: "q3", question: "To what vocation does chastity order sexuality?", options: ["To the repression of desire", "To conjugal love, lived in continence according to one's state of life", "To absolute sexual freedom", "Exclusively to procreation"], correct: 1, explanation: "\"Chastity means the successful integration of sexuality within the person\" (CCC 2337-2349)." },
  ],
    "31-work": [
    { id: "q1", question: "Is work a punishment for original sin?", options: ["Yes, it is entirely a consequence of sin", "No, work belongs to the original condition of the human being; sweat is the consequence of sin", "Yes, and Christians should avoid it", "Work has no relation to faith"], correct: 1, explanation: "\"Work proceeds from persons created in the image of God... Work is not a curse\" (CCC 2427; Gen 2:15)." },
    { id: "q2", question: "What is human work ordered toward besides earning a living?", options: ["Only accumulating wealth", "Honor, personal sanctification, and collaboration in the work of creation", "Only survival", "Mainly competition"], correct: 1, explanation: "\"Work can be a means of sanctification\" (CCC 2428)." },
    { id: "q3", question: "What fundamental right does the Church's social doctrine defend regarding work?", options: ["The right not to work", "The right to a just wage that allows the worker and his family to live a dignified life", "The right to unlimited enrichment", "The right to exploit workers"], correct: 1, explanation: "\"The just wage is the legitimate fruit of work\" (CCC 2434)." },
  ],
    "32-community": [
    { id: "q1", question: "Why cannot the Christian faith be lived in a purely individual way?", options: ["Because God created man as a social being and the Church is a body, not isolated individuals", "Because the Church arbitrarily imposes it", "Because individual faith has no value", "It can indeed be lived without community"], correct: 0, explanation: "The human person needs social life as a requirement of his nature (CCC 1878; 1 Cor 12)." },
    { id: "q2", question: "What impressed the pagans about the early Christians?", options: ["Their wealth and power", "Their great temples", "Their visible and concrete love: \"See how they love one another\"", "Their political influence"], correct: 2, explanation: "Tertullian testifies that the pagans said in amazement: \"See how they love one another\" (Apologeticum 39,7)." },
    { id: "q3", question: "How should the Christian community live solidarity with the poor?", options: ["Delegating all help to the state", "As a duty of justice and charity, seeing Christ in the poor", "Only if they prove they deserve help", "Only through prayer"], correct: 1, explanation: "\"It is a duty of justice and of charity.\" \"Whatever you did to these least brothers of mine, you did it to me\" (CCC 2443-2449; Mt 25:40)." },
  ],
    "33-christian-prayer": [
    { id: "q1", question: "According to the Catechism, what is prayer?", options: ["A mandatory ritual", "The elevation of the soul to God or the petition of suitable goods", "An Eastern meditation technique", "A duty exclusively for priests and religious"], correct: 1, explanation: "Saint John Damascene defines prayer as 'the elevation of the soul to God or the petition to God of suitable goods' (CCC 2559)." },
    { id: "q2", question: "From where does prayer spring, according to the Catechism?", options: ["From religious obligation", "From the human heart, from its joys and sorrows, from its search for God", "Only from reading the Bible", "Exclusively from the liturgy"], correct: 1, explanation: "Prayer springs from the sources of life: the heart, Scripture, the liturgy, and the theological virtues (CCC 2650-2662)." },
    { id: "q3", question: "What are the three major forms of prayer?", options: ["Vocal prayer, meditation, and contemplation", "Petition, praise, and thanksgiving", "The Our Father, the Hail Mary, and the Glory Be", "The Mass, the Rosary, and lectio divina"], correct: 0, explanation: "The three principal forms are vocal prayer, meditation, and contemplation (CCC 2699, 2721-2724)." },
  ],
    "34-sources-of-prayer": [
    { id: "q1", question: "According to the Catechism, what is the primary source of Christian prayer?", options: ["The liturgy of the Church", "The Word of God (Sacred Scripture)", "The monastic tradition", "The writings of the mystics"], correct: 1, explanation: "'The Word of God is the source of Christian prayer'; the Church exhorts the faithful to read Scripture because 'to be ignorant of Scripture is to be ignorant of Christ' (CCC 2653)." },
    { id: "q2", question: "What is 'lectio divina'?", options: ["A medieval prayer book", "The prayerful reading of Sacred Scripture in an atmosphere of silence and listening", "A theological treatise on contemplation", "The communal recitation of the Divine Office"], correct: 1, explanation: "Lectio divina is the prayerful reading of the Bible practiced since the Desert Fathers, with steps of reading, meditation, prayer, and contemplation (CCC 1177, 2708)." },
    { id: "q3", question: "Why is the liturgy a source of prayer?", options: ["Because it is the only valid prayer", "Because in the liturgy Christ himself prays and acts, uniting us to his prayer", "Because it is obligatory on Sundays", "Because it has beautiful music and hymns"], correct: 1, explanation: "In the liturgy it is Christ who prays, praises, and gives thanks; liturgical prayer is the prayer of the entire Church (CCC 1074, 2643)." },
  ],
    "35-the-contemplative-tradition": [
    { id: "q1", question: "What is Christian contemplation?", options: ["A technique of mental emptiness", "A state of trance or emotional ecstasy", "The simple and loving gaze upon God, a gift and a grace", "A practice exclusive to monks and hermits"], correct: 2, explanation: "Saint Teresa defines contemplation as 'a simple and loving gaze upon God.' It is a gift, not a technique (CCC 2709-2713)." },
    { id: "q2", question: "What is the battle of prayer according to the Catechism?", options: ["A physical struggle against visible enemies", "Resistance to distractions, dryness, and sloth in prayer", "A competition to see who prays the most", "The theological debate about the best way to pray"], correct: 1, explanation: "Prayer is a battle against ourselves, against distractions, dryness (acedia), and the temptation to abandon it (CCC 2726-2733)." },
    { id: "q3", question: "How does the Catechism respond to the objection 'I don't know how to pray'?", options: ["By saying that only the saints know how", "By affirming that the Holy Spirit himself prays in us and teaches us to pray", "By recommending reading spirituality manuals", "By indicating that prayer is not necessary for salvation"], correct: 1, explanation: "'We do not know how to pray as we ought, but the Spirit himself intercedes for us' (Rom 8:26; CCC 741, 2736)." },
  ],
    "36-our-father": [
    { id: "q1", question: "Why is the Our Father called 'the Lord's Prayer'?", options: ["Because it was composed by the apostles", "Because it was taught and handed on by Jesus himself", "Because it is the most ancient of all prayers", "Because it is only prayed at solemn Masses"], correct: 1, explanation: "'The Our Father is truly the summary of the whole Gospel,' the prayer that Jesus himself taught to his disciples (CCC 2761, 2773)." },
    { id: "q2", question: "What does it mean to call God 'Our Father' (Abba)?", options: ["That God is an authoritarian and distant figure", "An expression of filial trust, intimacy, and belonging to God's family", "That God is only the Father of Jesus, not ours", "That we can treat God with irreverent familiarity"], correct: 1, explanation: "Calling God Abba expresses the newness of Christian prayer: the trust and intimacy of children in the Son (CCC 2777-2780)." },
    { id: "q3", question: "What does 'your will be done' mean?", options: ["A passive resignation to fate", "The petition that God's loving plan be accomplished, uniting ourselves to Christ's obedience", "The desire to impose our will on God", "That God should do what we want"], correct: 1, explanation: "We ask that the design of God's benevolence be realized, uniting our will to that of Christ (CCC 2816-2825)." },
  ],
    "37-seven-petitions": [
    { id: "q1", question: "How are the seven petitions of the Our Father divided?", options: ["Four toward God and three toward us", "Three toward God (theological) and four toward us (human)", "All are directed exclusively to God", "It is an arbitrary division without meaning"], correct: 1, explanation: "The first three refer to God: his Name, his Kingdom, his will. The last four present our needs (CCC 2803-2806)." },
    { id: "q2", question: "What do we ask for in 'give us this day our daily bread'?", options: ["Only material bread", "Filial trust that expects from God daily nourishment and the Bread of Life (the Eucharist)", "Wealth and material abundance", "Only Eucharistic communion"], correct: 1, explanation: "We ask for earthly bread and the Bread of Life: the Eucharist, foretaste of the banquet of the Kingdom (CCC 2835-2837)." },
    { id: "q3", question: "What does 'forgive us our trespasses as we forgive those who trespass against us' mean?", options: ["That divine forgiveness depends on our merit", "That God's forgiveness and the forgiveness we give to our neighbor are inseparable; whoever does not forgive cannot receive forgiveness", "That God forgives unconditionally without expecting anything from us", "That we should forgive only those who deserve it"], correct: 1, explanation: "'This forgiveness cannot penetrate our heart if we have not forgiven those who have offended us' (CCC 2838-2845; Mt 6:14-15)." },
  ],
};


export function getQuiz(slug: string): Question[] | null {
  return QUIZZES[slug] || null;
}

export async function submitQuizScore(
  lessonPath: string,
  score: number,
  total: number
): Promise<void> {
  const supabase = getSupabase();
  if (!supabase) return;
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return;

  const pct = Math.round((score / total) * 100);
  const now = new Date().toISOString();

  await supabase.from("lesson_progress").upsert(
    {
      user_id: user.id,
      lesson_slug: lessonPath,
      quiz_score: pct,
      status: pct >= 70 ? "completed" : "in_progress",
    } as any,
    { onConflict: "user_id,lesson_slug" }
  );
}
